# Generated by Django 5.1.6 on 2025-02-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Task.project'),
            preserve_default=False,
        ),
    ]
